const ShopActionTypes = {
	UPDATE_BICYCLE: 'UPDATE_BICYCLE',
	FILTER_BY_PRICE: 'FILTER_BY_PRICE',
	FILTER_BY_MANUFACTURER: 'FILTER_BY_MANUFACTURER',
	FILTER_BY_COUNTRY: 'FILTER_BY_COUNTRY',
	FILTER_BY_REGION: 'FILTER_BY_REGION'
}

export default ShopActionTypes;