const ShopActionTypes = {
	FETCH_BICYCLES_START: 'FETCH_BICYCLES_START',
	FETCH_BICYCLES_SUCCESS: 'FETCH_BICYCLES_SUCCESS',
	FETCH_BICYCLES_FAILURE: 'FETCH_BICYCLES_FAILURE',
	FILTER_BY_PRICE: 'FILTER_BY_PRICE',
	FILTER_BY_MANUFACTURER: 'FILTER_BY_MANUFACTURER',
	FILTER_BY_COUNTRY: 'FILTER_BY_COUNTRY',
	FILTER_BY_REGION: 'FILTER_BY_REGION',
	TOGGLE_CAROUSEL: 'TOGGLE_CAROUSEL'
}

export default ShopActionTypes;