const ShopActionTypes = {
	FETCH_BICYCLES_START: 'FETCH_BICYCLES_START',
	FETCH_BICYCLES_SUCCESS: 'FETCH_BICYCLES_SUCCESS',
	FETCH_BICYCLES_FAILURE: 'FETCH_BICYCLES_FAILURE',
	FILTER_BY_PRICE: 'FILTER_BY_PRICE',
	FILTER_BY_MANUFACTURER: 'FILTER_BY_MANUFACTURER',
	FILTER_BY_COUNTRY: 'FILTER_BY_COUNTRY',
	FILTER_BY_REGION: 'FILTER_BY_REGION',
	TOGGLE_CAROUSEL: 'TOGGLE_CAROUSEL',
	DELETE_BICYCLE_START: 'DELETE_BICYCLE_START',
	DELETE_BICYCLE_SUCCESS: 'DELETE_BICYCLE_SUCCESS',
	DELETE_BICYCLE_ERROR: 'DELETE_BICYCLE_ERROR',
	HAS_BICYCLE_DELETED: 'HAS_BICYCLE_DELETED'
}

export default ShopActionTypes;