const SideNavActionTypes = {
	TOGGLE_SIDE_NAV: 'TOGGLE_SIDE_NAV',
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	ADD_ITEM: 'ADD_ITEM',
	CLEAR_ITEM_FROM_FAVOURITES: 'CLEAR_ITEM_FROM_FAVOURITES',
	CLEAR_FAVOURITES: 'CLEAR_FAVOURITES'
}

export default SideNavActionTypes;