const SideNavActionTypes = {
  TOGGLE_ACCOUNT_DROPDOWN: "TOGGLE_ACCOUNT_DROPDOWN",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_FAVOURITES: "CLEAR_ITEM_FROM_FAVOURITES",
  CLEAR_FAVOURITES: "CLEAR_FAVOURITES",
};

export default SideNavActionTypes;
