const SellFormTypes = {
  INPUT_CHANGE: "INPUT_CHANGE",
  SET_STEP: "SET_STEP",
  SET_MAP_MARKER: "SET_MAP_MARKER",
  ADDRESS: "address",
  COORDINATES: "coordinates",
  GET_MANUFACTURER_LIST_START: "GET_MANUFACTURER_LIST_START",
  GET_MANUFACTURER_LIST_FINISH: "GET_MANUFACTURER_LIST_FINISH",
  CLEAN_UP: "CLEAN_UP",
  VALIDATE_ALL_FIELDS: "VALIDATE_ALL_FIELDS",
};

export default SellFormTypes;
