const SellActionTypes = {
	IMAGE_UPLOAD_START: 'IMAGE_UPLOAD_START',
	IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
	BICYCLE_UPLOAD_START: 'BICYCLE_UPLOAD_START',
	UPLOAD_FINISHED: 'UPLOAD_FINISHED'
}

export default SellActionTypes;