const SellActionTypes = {
  IMAGE_UPLOAD_START: "IMAGE_UPLOAD_START",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  BICYCLE_UPLOAD_START: "BICYCLE_UPLOAD_START",
  UPLOAD_FINISHED: "UPLOAD_FINISHED",
  SUBMIT_SUCCESS: "SUBMIT_SUCCESS",
  SUBMIT_ERROR: "SUBMIT_ERROR",
  TOGGLE_SNACK: "TOGGLE_SNACK",
  INVALID_FORM: "INVALID_FORM",
};

export default SellActionTypes;
