const FavouritesActionTypes = {
	TOGGLE_FAVOURITES_HIDDEN: 'TOGGLE_FAVOURITES_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	CLEAR_ITEM_FROM_FAVOURITES: 'CLEAR_ITEM_FROM_FAVOURITES'
}

export default FavouritesActionTypes;