const UpdateActiontypes = {
  IMAGE_UPDATE_START: "IMAGE_UPDATE_START",
  IMAGE_UPDATE_SUCCESS: "IMAGE_UPDATE_SUCCESS",
  IMAGE_URL_UPDATE_START: "IMAGE_URL_UPDATE_START",
  IMAGE_URL_UPDATE_SUCCESS: "IMAGE_URL_UPDATE_SUCCESS",
};

export default UpdateActiontypes;
