const UpdateActiontypes = {
  IMAGE_UPDATE_START: "IMAGE_UPDATE_START",
  IMAGE_UPDATE_SUCCESS: "IMAGE_UPDATE_SUCCESS",
  IMAGE_URL_UPDATE_START: "IMAGE_URL_UPDATE_START",
  IMAGE_URL_UPDATE_SUCCESS: "IMAGE_URL_UPDATE_SUCCESS",
  IMAGE_DELETE_START: "IMAGE_DELETE_START",
  IMAGE_DELETE_SUCCESS: "IMAGE_DELETE_SUCCESS",
  SELECT_CURRENT: "SELECT_CURRENT",
};

export default UpdateActiontypes;
