const UpdateActiontypes = {
  IMAGE_UPDATE_START: "IMAGE_UPDATE_START",
  IMAGE_UPDATE_SUCCESS: "IMAGE_UPDATE_SUCCESS",
  IMAGE_URL_UPDATE_START: "IMAGE_URL_UPDATE_START",
  IMAGE_URL_UPDATE_SUCCESS: "IMAGE_URL_UPDATE_SUCCESS",
  IMAGE_DELETE_START: "IMAGE_DELETE_START",
  IMAGE_DELETE_SUCCESS: "IMAGE_DELETE_SUCCESS",
  SELECT_CURRENT: "SELECT_CURRENT",
  BICYCLE_UPDATE_START: "BICYCLE_UPDATE_START",
  BICYCLE_UPDATE_SUCCESS: "BICYCLE_UPDATE_SUCCESS",
  INVALID_UPDATE_FORM: "INVALID_UPDATE_FORM",
  GET_DEFAULT: "GET_DEFAULT",
  TOGGLE_UPDATE_SNACKBAR: "TOGGLE_UPDATE_SNACKBAR",
};

export default UpdateActiontypes;
